# general settings
name: tmp_base
model_type: VideoRecurrentModel
scale: 4
num_gpu: auto  # official: 2 GPUs
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: REDS
    type: REDSRecurrentDataset
    dataroot_gt: dataset/REDS/train/train_sharp
    dataroot_lq: dataset/REDS/train/train_sharp_bicubic/X4
    meta_info_file: basicsr/data/meta_info/meta_info_REDS_GT.txt
    val_partition: REDS4  # set to 'official' when use the official validation partition
    test_mode: False
    io_backend:
      type: disk

    num_frame: 15
    gt_size: 256
    interval_list: [1]
    random_reverse: true
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    # batch_size_per_gpu: 4
    batch_size_per_gpu: 1 # only for testing code
    dataset_enlarge_ratio: 200
    prefetch_mode: ~

# network structures
network_g:
  type: TMP
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_frame: 15
  num_extract_block: 3
  num_reconstruct_block: 10
  center_frame_idx: None
  hr_in: False

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000, 300000]
    restart_weights: [1, 1]
    eta_min: !!float 1e-7

  total_iter: 600000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 50e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
