"""
Vid4-BD evaluation for the BD weights: online frame-by-frame inference with
hidden-state propagation. Metrics: PSNR/SSIM (Y channel, crop_border=0).

Usage (repo root):
    python scripts/test_tmp_vid4_bd.py --weights models/TMP_BD_Vimeo90k_Vid4.pth \
        --gt_root <GT dir> --lq_root <BDx4 dir>
LQ data should be generated by scripts/data_preparation/generate_LR_BDx4.py.
"""
import argparse
import json
import os
import sys

import cv2
import numpy as np
import torch

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
os.chdir(REPO)
from basicsr.archs.tmpbd_arch import TMPBD  # noqa: E402
from basicsr.metrics.psnr_ssim import calculate_psnr, calculate_ssim  # noqa: E402
from basicsr.utils.img_util import tensor2img  # noqa: E402


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--weights', required=True)
    ap.add_argument('--gt_root', required=True)
    ap.add_argument('--lq_root', required=True)
    ap.add_argument('--out', default='results_vid4_bd.json')
    args = ap.parse_args()
    net = TMPBD()
    ck = torch.load(args.weights, map_location='cpu')
    ck = ck['params_ema'] if 'params_ema' in ck else (ck['params'] if 'params' in ck else ck)
    net.load_state_dict(ck, strict=True)
    net = net.cuda().eval()
    out = {'seqs': {}}
    allp, alls = [], []
    for seq in sorted(os.listdir(args.gt_root)):
        gts = sorted(os.listdir(os.path.join(args.gt_root, seq)))
        lqs = sorted(os.listdir(os.path.join(args.lq_root, seq)))
        hidden, ps, ss = None, [], []
        for lf, gf in zip(lqs, gts):
            lq = cv2.imread(os.path.join(args.lq_root, seq, lf))
            rgb = cv2.cvtColor(lq, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
            x = torch.from_numpy(rgb.transpose(2, 0, 1))[None, None].cuda()
            with torch.no_grad():
                sr, hidden = net(x, hidden, return_hs=True)
            gt = cv2.imread(os.path.join(args.gt_root, seq, gf))
            si = tensor2img(sr[0, 0])
            ps.append(calculate_psnr(si, gt, crop_border=0, input_order='HWC', test_y_channel=True))
            ss.append(calculate_ssim(si, gt, crop_border=0, input_order='HWC', test_y_channel=True))
        out['seqs'][seq] = {'psnr': float(np.mean(ps)), 'ssim': float(np.mean(ss)), 'n': len(ps)}
        allp += ps
        alls += ss
        print(seq, round(float(np.mean(ps)), 4), round(float(np.mean(ss)), 4), flush=True)
    out['total'] = {'psnr': float(np.mean(allp)), 'ssim': float(np.mean(alls))}
    with open(args.out, 'w') as f:
        json.dump(out, f, indent=1)
    print('TOTAL', round(out['total']['psnr'], 4), round(out['total']['ssim'], 4))


if __name__ == '__main__':
    main()
